# -*- coding: utf-8 -*-
"""Requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6JcH_9yeGAln_055YbLIcY42gynqgdK
"""

streamlit
yfinance
pandas
pandas_ta
mplfinance
matplotlib